/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telasCodigos;

import java.awt.Color;
import javax.swing.JOptionPane;
import sistemaDeEstoque.Dados;
import sistemaDeEstoque.Fornecedor;

/**
 *
 * @author Kook Ho
 */
public class CadastrarFornecedor extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarFornecedor
     */
    public CadastrarFornecedor() {
        initComponents();
    }
    
    String temp;
    
    private boolean checaCNPJ(){
        jlCNPJ.setForeground(Color.black);
        temp = tfCNPJ.getText();
        try{
            int preco = Integer.parseInt(this.tfCNPJ.getText());
            if(this.temp.length() != 14){
                jlCNPJ.setForeground(Color.red);
                return false;
            }
            
            return true;
        }catch(NumberFormatException e){
            jlCNPJ.setForeground(Color.red);
            
            return false;
        }
    }
    
    private boolean checaCamposVazios(){
        if(this.tfRazaoSoc.getText().equals("") || this.tfCNPJ.getText().equals("") || this.tfProdForn.getText().equals("")){
           if(this.tfRazaoSoc.getText().equals("")){
               jlRazaoSocial.setForeground(Color.red);
           }else{
               jlRazaoSocial.setForeground(Color.black);
           }
           if(this.tfProdForn.getText().equals("")){
               jlProdForn.setForeground(Color.red);
           }else{
               jlProdForn.setForeground(Color.black);
           }
           if(this.tfCNPJ.getText().equals("")){
               jlCNPJ.setForeground(Color.red);
           }else{
               jlCNPJ.setForeground(Color.black);
           }
            return false; 
        }
        else{
            jlCNPJ.setForeground(Color.black);
            jlProdForn.setForeground(Color.black);
            jlRazaoSocial.setForeground(Color.black);
            
            return true;
        }
    }
    
    private void limpaCampos(){
        this.tfRazaoSoc.setText("");
        this.tfProdForn.setText("");
        this.tfCNPJ.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        btCadFornecedor = new javax.swing.JButton();
        jlRazaoSocial = new javax.swing.JLabel();
        jlCNPJ = new javax.swing.JLabel();
        jlProdForn = new javax.swing.JLabel();
        tfRazaoSoc = new javax.swing.JTextField();
        tfCNPJ = new javax.swing.JTextField();
        tfProdForn = new javax.swing.JTextField();
        btLimpar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTitulo.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabelTitulo.setText("Cadastrar Novo Fornecedor");

        btCadFornecedor.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        btCadFornecedor.setText("Cadastrar");
        btCadFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadFornecedorActionPerformed(evt);
            }
        });

        jlRazaoSocial.setFont(new java.awt.Font("Bahnschrift", 1, 11)); // NOI18N
        jlRazaoSocial.setText("Razão Social:");

        jlCNPJ.setFont(new java.awt.Font("Bahnschrift", 1, 11)); // NOI18N
        jlCNPJ.setText("CNPJ:");

        jlProdForn.setFont(new java.awt.Font("Bahnschrift", 1, 11)); // NOI18N
        jlProdForn.setText("Produto fornecido:");

        btLimpar.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btCancelar.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabelTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(jlRazaoSocial))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jlProdForn)
                                    .addComponent(jlCNPJ))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfRazaoSoc, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                            .addComponent(tfProdForn)
                            .addComponent(tfCNPJ)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(btCadFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabelTitulo)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlRazaoSocial)
                    .addComponent(tfRazaoSoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCNPJ)
                    .addComponent(tfCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlProdForn)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfProdForn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCadFornecedor)
                    .addComponent(btLimpar)
                    .addComponent(btCancelar))
                .addGap(28, 28, 28))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btCadFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadFornecedorActionPerformed
        if(checaCamposVazios()){
            if(checaCNPJ()){
                Dados.Forn.add(
                new Fornecedor(
                        tfRazaoSoc.getText(),
                        tfProdForn.getText(),
                        tfCNPJ.getText()  
                 ));
                JOptionPane.showMessageDialog(null, "Fornecedor Cadastrado com Sucesso!");
                System.out.println(Dados.Forn);
                limpaCampos();
            }else{
                JOptionPane.showMessageDialog(null, "CNPJ está incorreto!");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Campo Vazio!");
        }
    }//GEN-LAST:event_btCadFornecedorActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limpaCampos();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        CadastrarFornecedor.this.setVisible(false);
        new TelaInicial().setVisible(true);
    }//GEN-LAST:event_btCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarFornecedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadFornecedor;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btLimpar;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jlCNPJ;
    private javax.swing.JLabel jlProdForn;
    private javax.swing.JLabel jlRazaoSocial;
    private javax.swing.JTextField tfCNPJ;
    private javax.swing.JTextField tfProdForn;
    private javax.swing.JTextField tfRazaoSoc;
    // End of variables declaration//GEN-END:variables
}
